### ISSUE TITLE
Sentry – LivesessionError: Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by aleksandr-shevchenko-0** [livesession/livesession-sdk#16]
Hello, 
I'm catching this error in sentry:
`LivesessionError: Cannot read properties of null (reading 'getAttribute').` 

Presumably the problem is in some extension for chrome. 

Have you encountered this error?
Is there any way to fix it on our side or yours. 
Or is the only option is to ignore it?

`"@livesession/sdk": "^1.1.4"`

**Comment by aleksandr-shevchenko-0** [comment]
<img width="835" alt="image" src="https://github.com/livesession/livesession-sdk/assets/134926474/e7ee8ce6-532a-4923-ba9e-950f15cd4f80">

<img width="854" alt="image" src="https://github.com/livesession/livesession-sdk/assets/134926474/7ddead8e-5c16-4a85-8d93-d954426d3e7f">

<img width="871" alt="image" src="https://github.com/livesession/livesession-sdk/assets/134926474/9a815244-7797-4465-8ae7-e19aea5d5f28">

**Comment by zdunecki** [comment]
Hi @aleksandr-shevchenko-0 thank you for reaching out us. 

Do you know if this issue crash your app? If you have more details (e.g list of sessions where this happened) please contact with us via Intercom or an email (support@livesession.io) to give us more information.

While a fix for that can be easy it's better to know if it cause more problem, more than error logs on Sentry.

Best,

**Comment by aleksandr-shevchenko-0** [comment]
Hi @zdunecki 
Any news?

**Comment by zdunecki** [comment]
@aleksandr-shevchenko-0 

Let's in touch on email.

**Comment by zdunecki** [comment]
@aleksandr-shevchenko-0 

I'm going to close this issue. If you still have problems, just get back to us.

Best
